[build]
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"  # "elf2uf2-rs -d"
# runner = "elf2uf2-rs -d"

rustflags = [
#     "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tlink-rp.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "linker=flip-link",
#     "-C", "inline-threshold=5",
#     "-C", "no-vectorize-loops",
]

[env]
# trace, info, warn, or error
DEFMT_LOG = "trace"
